/*
 * verify_fixtures.mjs
 * ---------------------------------------------------------------------------
 * Single-source-of-truth check: re-implements the calculator math in JS and
 * compares it to the fixtures generated by the hlaclinval R package
 * (data-raw/gen_fixtures.R). If the browser widgets and the R package ever
 * diverge, this fails.
 *
 *   node verify_fixtures.mjs hlaclinval_fixtures.json
 *
 * The functions below MUST stay identical to the math embedded in the
 * Quarto widgets (PPV/NPV/NNT and exact-Fisher power).
 */

import { readFileSync } from "node:fs";

/* ---- predictive layer (mirrors the PPV/NPV/NNT widget) ---- */
function ppvNpvNnt(s, f, I) {
  const ppv = Math.min(1, (s * I) / f);
  const npv = 1 - ((1 - s) * I) / (1 - f);
  const nnt = s * I > 0 ? 1 / (s * I) : Infinity;
  const ceiling = Math.min(1, I / f);
  return { ppv, npv, nnt, carrier_risk: ppv, ppv_ceiling: ceiling };
}

/* ---- power layer (mirrors the exact-Fisher widget) ---- */
const LF = [0];
function buildLF(n) { for (let i = LF.length; i <= n; i++) LF[i] = LF[i - 1] + Math.log(i); }
function lc(n, k) { if (k < 0 || k > n || n < 0) return -Infinity; return LF[n] - LF[k] - LF[n - k]; }
function db(k, n, p) {
  if (p <= 0) return k === 0 ? 1 : 0;
  if (p >= 1) return k === n ? 1 : 0;
  return Math.exp(lc(n, k) + k * Math.log(p) + (n - k) * Math.log(1 - p));
}
function caseProp(or, pc) { return (or * pc) / (1 - pc + or * pc); }
function fisherP(x1, x2, nC, nT) {
  const N = nC + nT, m1 = x1 + x2, dn = lc(N, nC);
  const lo = Math.max(0, nC - (N - m1)), hi = Math.min(nC, m1);
  const obs = Math.exp(lc(m1, x1) + lc(N - m1, nC - x1) - dn);
  let p = 0;
  for (let k = lo; k <= hi; k++) {
    const pk = Math.exp(lc(m1, k) + lc(N - m1, nC - k) - dn);
    if (pk <= obs * (1 + 1e-7)) p += pk;
  }
  return p;
}
function buildReject(nC, nT, alpha) {
  buildLF(nC + nT);
  const R = [];
  for (let x1 = 0; x1 <= nC; x1++) {
    R[x1] = [];
    for (let x2 = 0; x2 <= nT; x2++) R[x1][x2] = fisherP(x1, x2, nC, nT) <= alpha;
  }
  return R;
}
function power(nC, nT, pc, or, alpha, reject) {
  const p1 = caseProp(or, pc);
  const w1 = [], w2 = [];
  for (let x = 0; x <= nC; x++) w1[x] = db(x, nC, p1);
  for (let x = 0; x <= nT; x++) w2[x] = db(x, nT, pc);
  let pw = 0;
  for (let x1 = 0; x1 <= nC; x1++)
    for (let x2 = 0; x2 <= nT; x2++)
      if (reject[x1][x2]) pw += w1[x1] * w2[x2];
  return Math.min(1, pw);
}
function mdor(nC, nT, pc, alpha, target) {
  const reject = buildReject(nC, nT, alpha);
  if (power(nC, nT, pc, 80, alpha, reject) < target) return null;
  if (power(nC, nT, pc, 1.0001, alpha, reject) >= target) return 1;
  let lo = 1.0001, hi = 80;
  for (let i = 0; i < 40; i++) {
    const mid = (lo + hi) / 2;
    if (power(nC, nT, pc, mid, alpha, reject) >= target) hi = mid; else lo = mid;
  }
  return hi;
}

/* ---- compare to fixtures ---- */
const path = process.argv[2] || "hlaclinval_fixtures.json";
const fx = JSON.parse(readFileSync(path, "utf8"));
let pass = 0, fail = 0;
const REL = 1e-3; // relative tolerance (widgets round; R rounds to 6 dp)

function close(a, b, tol = REL) {
  if (a === null || b === null || !isFinite(a) || !isFinite(b)) return a === b || (!isFinite(a) && !isFinite(b));
  const denom = Math.max(1e-9, Math.abs(b));
  return Math.abs(a - b) / denom <= tol;
}
function check(label, got, want, tol) {
  if (close(got, want, tol)) { pass++; }
  else { fail++; console.error(`FAIL ${label}: js=${got} r=${want}`); }
}

for (const c of fx.predictive) {
  const r = ppvNpvNnt(c.sensitivity, c.carriage, 1 / c.incidence_one_in);
  const tag = `PPV[s=${c.sensitivity},f=${c.carriage},1/${c.incidence_one_in}]`;
  check(`${tag}.ppv`, r.ppv, c.ppv);
  check(`${tag}.npv`, r.npv, c.npv);
  check(`${tag}.nnt`, r.nnt, c.nnt);
  check(`${tag}.ceiling`, r.ppv_ceiling, c.ppv_ceiling);
}

for (const c of fx.power) {
  const reject = buildReject(c.n_case, c.n_ctrl, c.alpha);
  for (const pt of c.power_at_or) {
    check(`POW[n=${c.n_case},a=${c.alpha},or=${pt.or}]`,
          power(c.n_case, c.n_ctrl, c.carriage, pt.or, c.alpha, reject), pt.power);
  }
  // MDOR via bisection; looser tolerance since R uses uniroot
  const md = mdor(c.n_case, c.n_ctrl, c.carriage, c.alpha, 0.80);
  check(`MDOR[n=${c.n_case},a=${c.alpha}]`, md, c.mdor_80, 5e-3);
}

console.log(`\n${pass} passed, ${fail} failed (${fx.predictive.length} predictive + ${fx.power.length} power fixtures)`);
process.exit(fail ? 1 : 0);
